"""empty message

Revision ID: 20f4e73166e2
Revises: f5002b4e303f
Create Date: 2022-06-16 17:30:44.642493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f4e73166e2'
down_revision = 'f5002b4e303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'teacher_id')
    # ### end Alembic commands ###
