"""empty message

Revision ID: 52744b6e35bd
Revises: 
Create Date: 2022-06-29 19:01:02.104056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52744b6e35bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('subjects1', sa.String(length=100), nullable=False),
    sa.Column('subjects2', sa.String(length=100), nullable=True),
    sa.Column('subjects3', sa.String(length=100), nullable=True),
    sa.Column('subjects4', sa.String(length=100), nullable=True),
    sa.Column('why_you_teach', sa.String(length=200), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('fun_info', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('introduction', sa.String(length=2000), nullable=False),
    sa.Column('written_content', sa.String(length=5000), nullable=False),
    sa.Column('summary', sa.String(length=1250), nullable=False),
    sa.Column('key_word1', sa.String(length=30), nullable=True),
    sa.Column('key_word2', sa.String(length=30), nullable=True),
    sa.Column('key_word3', sa.String(length=30), nullable=True),
    sa.Column('question1', sa.String(length=500), nullable=True),
    sa.Column('question2', sa.String(length=500), nullable=True),
    sa.Column('question3', sa.String(length=500), nullable=True),
    sa.Column('question4', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=50000), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    op.drop_table('user')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
