"""empty message

Revision ID: 5d90e3143874
Revises: 20f4e73166e2
Create Date: 2022-06-22 21:39:38.766851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d90e3143874'
down_revision = '20f4e73166e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_teacher_id_fkey', 'content', type_='foreignkey')
    op.drop_column('content', 'teacher_id')
    op.add_column('teacher', sa.Column('subjects', sa.String(length=100), nullable=False))
    op.drop_column('teacher', 'subjects2')
    op.drop_column('teacher', 'subjects3')
    op.drop_column('teacher', 'subjects1')
    op.drop_column('teacher', 'subjects4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('subjects4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('subjects1', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('subjects3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('subjects2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'subjects')
    op.add_column('content', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('content_teacher_id_fkey', 'content', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
