"""empty message

Revision ID: f5002b4e303f
Revises: f728f0b31302
Create Date: 2022-06-15 11:19:49.174441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5002b4e303f'
down_revision = 'f728f0b31302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('subjects1', sa.String(length=100), nullable=False))
    op.add_column('teacher', sa.Column('subjects2', sa.String(length=100), nullable=True))
    op.add_column('teacher', sa.Column('subjects3', sa.String(length=100), nullable=True))
    op.add_column('teacher', sa.Column('subjects4', sa.String(length=100), nullable=True))
    op.drop_column('teacher', 'subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('subjects', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('teacher', 'subjects4')
    op.drop_column('teacher', 'subjects3')
    op.drop_column('teacher', 'subjects2')
    op.drop_column('teacher', 'subjects1')
    # ### end Alembic commands ###
