"""empty message

Revision ID: fcb09eb33b74
Revises: 52744b6e35bd
Create Date: 2022-06-30 15:06:38.968821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb09eb33b74'
down_revision = '52744b6e35bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('avatar', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'student', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'avatar')
    # ### end Alembic commands ###
